stages:
  - build
  - deploy

build artifacts:
  stage: build
  variables:
    VERSION: ${CI_COMMIT_SHA}
  tags:
    - shell
  artifacts:
    paths:
      - ./themes.zip
      - ./hanko-plugin-keycloak-ear/target/hanko-plugin-keycloak.ear
    expire_in: 1 week
  script:
    - ./build.sh

deploy develop:
  stage: deploy
  only:
    - master
  tags:
    - shell
  environment:
    name: develop
    url: https://auth.develop.hanko.io/
  script:
    - git clone git@gitlab.com:hanko/hanko-infrastructure-keycloak.git
    - cd hanko-infrastructure-keycloak
    - git checkout master
    - cp ../themes.zip hanko-plugin/themes.zip
    - cp ../hanko-plugin-keycloak-ejb/target/hanko-plugin-keycloak-ejb-0.2-SNAPSHOT.ejb hanko-plugin/hanko-plugin-keycloak.ejb
    - git add .
    - git commit -m "[hanko-keycloak-plugin] update develop version to ${CI_COMMIT_SHA}"
    - git push origin master
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo ${SSH_PRIVATE_KEY} | base64 --decode)
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - git config --global user.name ${GITLAB_USER_NAME}
